models.py
from datetime import datetime
from time import time
import re
from app import db


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    # mainimage = db.Column(db.String(100))
    # category = db.Column(db.String(100))
    slug = db.Column(db.String(255), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime)
    default = datetime.now

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()
    
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time))

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'
    
class Portfolio(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    mainimage = db.Column(db.String(100))
    smallimage = db.Column(db.String(100))
    client = db.Column(db.String(100))
    role = db.Column(db.String(100))
    product = db.Column(db.String(100))
    durations = db.Column(db.String(100))
    tool = db.Column(db.String(100))
    link = db.Column(db.String(100))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    def __repr__(self):
        return f'<Portfolio id: {self.id}, title: {self.title}>'

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager


from config import Config

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)

migrate = Migrate(app,db) 
manager = Manager(app)

manager.add_command('db', MigrateCommand)

main.py
from app import app, db
import views
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def posts_list():
    posts = Post.query.all()
    return render_template('posts/blog.html', posts = posts)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    return render_template('posts/blog-post.html', post=post)

views.py
from app import app
from flask import render_template, redirect, request
from key import password
from email.mime.text import MIMEText
import smtplib
from models import Portfolio

@app.route('/')
def index():
    portfolio = Portfolio.query.all()
    return render_template('index.html',portfolio=portfolio)

@app.route('/contact')
def contact():
    return render_template('contact.html')

@app.route('/submit', methods=['POST'])
def submit():
    name = request.form.get("name")
    email = request.form.get('email')
    message = request.form.get('message')
    email_body = f'''
    You have received an message from {name}
    with email address {email}
    <blockquote>
    {message}
    </blockquote>
    '''
    subject = f'Get in Touch from {name}'
    sender= 'therealakarexcel@gmail.com'
    recipient = 'developerexcela@gmail.com'
    
    # Create an email message
    msg = MIMEText(email_body, "html")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
   
    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.login(sender, password)
        smtp.sendmail(sender, recipient, msg.as_string())
        return redirect('/')

posts/templates/posts/blog-post.html
<!DOCTYPE html>
<html lang="en">
   
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="preconnect" href="https://fonts.googleapis.com/">
      <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
      <title>{{post.title}}</title>
      <!-- Main CSS File -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">
      <!-- Main Color File -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/skins/orange.css')}}">
   </head>
   <body class="blog-page">
      <!-- Loader Starts -->
      <div class="loader-wrapper">
         <div class="loader">
         </div>
         <div class="loader-section section-left"></div>
         <div class="loader-section section-right"></div>
         </div>
      <!-- Loader Ends -->
      <!-- Blog Page Starts -->
      <div class="blog-content">
        <h1 class="title-post">
            {{post.title}}
        </h1>
        <div class="blog-container">
              <!-- Content Starts -->
              <div class="main-post">
                <div class="meta">
                    <div>
                       <i class="icon-calendar"></i>
                       <span>9 Apr 2022</span>
                    </div>
                    <div>
                       <i class="icon-price-tag"></i>
                       <span>wordpress, business</span>
                    </div>
                    <div>
                       <i class="icon-bubbles2"></i>
                       <span>17 comments</span>
                    </div>
                 </div>
                <img src="img/blog/blog1.jpg" alt="Blog image">
                <div class="post-content">
                   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                   </p>
                   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum
                      dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
                      aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                   </p>
                   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum
                      dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
                      aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                   </p>
                </div>
              </div>
            
            <!-- Content Ends -->
        </div>
     </div>
     <!-- Blog Page Ends -->
      <!-- Animated Layers Starts -->
      <div class="layers active-layer opacity-0">
         <div></div>
         <div></div>
         <div></div>
         <div></div>
         <div></div>
      </div>
      <div class="layers not-active-layer">
         <div></div>
         <div></div>
         <div></div>
         <div></div>
         <div></div>
      </div>
      <!-- Animated Layers Ends -->
      <!-- Template JS File -->
      <script src="{{url_for('static', filename='js/custom.js')}}"></script>
   </body>
</html>

posts/templates/posts/blog.html
<!DOCTYPE html>
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="preconnect" href="https://fonts.googleapis.com/">
      <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
      <title>Blog - Excel Capstone project</title>
      <!-- Main CSS File -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">
      <!-- Main Color File -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/skins/orange.css')}}">
   </head>
   <body class="blog-page">
      <!-- Loader Starts -->
      <div class="loader-wrapper">
         <div class="loader">
         </div>
         <div class="loader-section section-left"></div>
         <div class="loader-section section-right"></div>
         </div>
      <!-- Loader Ends -->
      <!-- Blog Page Starts -->
      <div class="blog-content">
        <h1>
           My Blog
        </h1>
        <div class="blog-container">
              <!-- Post Starts -->
              {% for post in posts %}
              <div class="post">
                <a href="{{url_for('posts.post_detail',slug=post.slug)}}">
                   <span class="img-holder">
                   <img src="{{url_for('static',filename='img/blog/blog1.jpg')}}" alt="">
                   </span>
                   <div class="content">
                      <span class="category">design</span>
                      <span class="post-title">
                      {{post.title}}
                      </span>
                      <p>
                        {{post.body}}    
                      </p>
                   </div>
                </a>
               </div>
               {% endfor %}
              <!-- Post Ends -->
              <!-- Load More Starts -->
              <div class="loadmore">
                  <span>Load More Posts</span>
              </div>
              <!-- Load More Ends -->
        </div>
     </div>
     <!-- Blog Page Ends -->
      <!-- Animated Layers Starts -->
      <div class="layers active-layer opacity-0">
         <div></div>
         <div></div>
         <div></div>
         <div></div>
         <div></div>
      </div>
      <div class="layers not-active-layer">
         <div></div>
         <div></div>
         <div></div>
         <div></div>
         <div></div>
      </div>
      <!-- Animated Layers Ends -->
      <script src="{{url_for('static', filename='js/custom.js')}}"></script>
   </body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
   
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="preconnect" href="https://fonts.googleapis.com/">
      <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
      <title>Excel capstone project - Get in touch</title>
      <!-- Main CSS File -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">
      <!-- Main Color File -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/skins/orange.css')}}">

   </head>
   <body class="contact-page">

        <div class="contact-container">
            <h1>Get in <span>touch</span></h1>
            <hr>
            <div class="content-container">             
                <div class="social-box">
                    <div class="contact-social">
                        <i class="icon-youtube"></i>
                        <a href="https://www.youtube.com/@akar_excel" target="_blank">@akar_excel</a>
                    </div>
                    <div class="contact-social">
                        <i class="icon-github"></i>
                        <a href="https://github.com/AkarExcel" target="_blank">@akarexcel</a>
                    </div>
                    <div class="contact-social">
                        <i class="icon-linkedin"></i>
                        <a href="https://www.linkedin.com/in/excel-akar" target="_blank">@excel-akar</a>
                    </div>
                    <div class="contact-social">
                        <i class="icon-twitter"></i>
                        <a href="http://twitter.com/_Akar_Excel" target="_blank">@_akar_excel</a>
                    </div>
                </div>
                <form class="contact-form" action="/submit" method="post">
                    <div class="contact-field-a">
                        <input type="text" class="contact-name" name="name" id="name" required placeholder="name">
                        <input type="email" class="contact-email" name="email" id="email" required placeholder="email">
                    </div>
                    <textarea class="contact-message" name="message" placeholder="message" id="message" cols="30" rows="10" required></textarea>
                    <button class="btn-primary contact-btn" type="submit" >Send Message</button>
                </form>
            </div>
        </div>

        <!-- Template JS File -->
        <script src="{{url_for('static', filename='js/custom.js')}}"></script>
    </body>
     
     </html>